### ISSUE TITLE
docker_spring-boot-jpa-docker-webapp_1 exited with code 1

### ISSUE THREAD

**Issue by ishantanu** [g00glen00b/spring-samples#1]
This is what I am getting when is ran docker-compose up after maven build

docker_spring-boot-jpa-docker-webapp_1 exited with code 1

However mysql container didnt threw any error.
What could be the possible reason for this? I think there might be some connection issues when webapp container tried establishing connection with database container. But the webapp container has the ip of database conmtainer in /etc/hosts

**Comment by g00glen00b** [comment]
This is weird. I've tried it myself and I didn't encounter any issues. Could you tell me what version of Docker you're using and on what OS you're running it? Can you also check if you pulled the latest commit? I updated the version of the Maven plugin for Docker in 6b884129f3986bbb94b019e98b19de5367235c1e.

While deploying the container on Bluemix (PaaS) I did notice that the network was only available after a while. So I improved the Dockerfile a bit for the Bluemix example to keep polling the database for a while until it's able to connect, though I never encounter such issues locally. I suggest looking at https://github.com/g00glen00b/spring-samples/tree/master/spring-boot-jpa-docker-bluemix-webapp/src/main/docker, perhaps it allows you to solve this issue.
