### ISSUE TITLE
Controller & Type Registry to parse the schema

### ISSUE THREAD

**Issue by benudhar03** [g00glen00b/spring-samples#39]
Need bit help on the mentioned title.

**Comment by g00glen00b** [comment]
Could you go a bit further into detail about what you need help with?

**Comment by benudhar03** [comment]
Here is the link of ur project.
https://github.com/g00glen00b/spring-samples/tree/master/spring-boot-graphql/src/main
So all I wanted to know that where is ur controller class and type registry. Bcz I want to see how have u been parsing the schema in side of ur service.

Bcz If u are implementing GraphQLMutationResolver in ur class then where have u used the class. All I need how are u returning the runtime wiring of the Mutation.

**Comment by g00glen00b** [comment]
You don't need to define a controller or a type registry with the GraphQL Spring boot kickstarter. It automatically infers which Java types correlate to which GraphQL types by parsing the schema and the resolvers.

The schema can be found in [src/main/resources/types.graphhqls](https://github.com/g00glen00b/spring-samples/blob/master/spring-boot-graphql/src/main/resources/types.graphqls) and the matching resolvers can be found in [QueryResolver](https://github.com/g00glen00b/spring-samples/blob/master/spring-boot-graphql/src/main/java/be/g00glen00b/springbootgraphql/QueryResolver.java) and [MutationResolver](https://github.com/g00glen00b/spring-samples/blob/master/spring-boot-graphql/src/main/java/be/g00glen00b/springbootgraphql/MutationResolver.java).
