### ISSUE TITLE
Spring boot solr batch

### ISSUE THREAD

**Issue by talhaouianas** [g00glen00b/spring-samples#42]
Hello
when i run your code Spring boot solr batch, i get this error.
can you help me to fixe this issue?
![spring_boot_solr_batch](https://user-images.githubusercontent.com/65512185/170819275-50816564-24bb-4607-aef2-a3e40a309162.PNG)

**Comment by g00glen00b** [comment]
I'm using Lombok in that example. Make sure to enable the Lombok plugin/annotation processing in IntelliJ.

**Comment by talhaouianas** [comment]
Thanks you
